name: Redoc and push files to bucket

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: redoc-cli
      uses: seeebiii/redoc-cli-github-action@v10
      with:
        args: 'bundle api.yml --options theme.json --output index.html'
        
    - name: Copy index.html to s3 bucket developer.nubadoo.com
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: 'index.html'
        dest: 's3://developer.nubadoo.com/index.html'
        
    - name: Copy logo.png to s3 bucket developer.nubadoo.com
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: 'logo.png'
        dest: 's3://developer.nubadoo.com/logo.png'
